//! Per-project configuration: `lambo.yml`.
//!
//! A `lambo.yml` at the project root tells Lambo everything it needs to run
//! the project: which PHP to use, which server fronts it, which document root
//! to serve, whether a database is provisioned. `lambo init` generates the
//! file from automatic detection (see [`crate::detect`]); afterwards a
//! teammate only needs `lambo up`.
//!
//! The canonical shape is the one the documentation shows:
//!
//! ```yaml
//! name: my-project
//! php: 8.4
//! server:
//!   kind: apache
//!   port: 8080
//!   document_root: public
//! database:
//!   kind: mariadb
//!   port: 3306
//! open_browser: true
//! ```
//!
//! Two rules make these files safe to commit:
//!
//! 1. **Every field is optional.** A file written by an older Lambo keeps
//!    parsing on a newer one, and omitted values inherit from the global
//!    configuration - so a project file never has to repeat machine
//!    specifics.
//! 2. **No absolute paths.** `document_root` is always relative to the
//!    project root, which keeps the file portable between Windows and Unix
//!    checkouts of the same repository.

use std::collections::BTreeMap;
use std::fs;
use std::io::ErrorKind;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::config::{Config, DatabaseKind, ServerKind};
use crate::error::{Error, Result};
use crate::naming;
use crate::platform;
use crate::version::VersionSpec;
use crate::yaml;

/// Header written above generated files.
const HEADER: &str = "\
# Lambo PHP project configuration
# Reference: docs/lambofile.md in the Lambo PHP repository
# Generated by `lambo init`; edit freely - `lambo up` honours this file.
";

/// Name of the per-project configuration file.
pub const FILE_NAME: &str = "lambo.yml";

/// Name used by king-PHP, still read for migration.
pub const LEGACY_FILE_NAME: &str = "kingphp.yml";

/// Server settings of one project.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default)]
pub struct ServerSettings {
    /// Which server fronts the project.
    ///
    /// Absent means "inherit `server.kind` from the global configuration",
    /// which is what the documented hierarchy global → project requires. To
    /// pin a server for one project, name it here.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<ServerKind>,
    /// HTTP port; inherits `server.port` from the global config when absent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub port: Option<u16>,
    /// HTTPS port; inherits `server.https_port` when absent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub https_port: Option<u16>,
    /// Document root relative to the project root (`public`, `.`, `web`).
    pub document_root: String,
}

impl Default for ServerSettings {
    fn default() -> Self {
        Self {
            kind: None,
            port: None,
            https_port: None,
            document_root: ".".to_owned(),
        }
    }
}

/// Database settings of one project.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default)]
pub struct DatabaseSettings {
    /// Engine; `none` disables provisioning for this project, and an absent
    /// value inherits `database.kind` from the global configuration.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<DatabaseKind>,
    /// TCP port; inherits `database.port` from the global config when absent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub port: Option<u16>,
    /// Database name; defaults to the slugified project name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// Project-level configuration parsed from `lambo.yml`.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default)]
pub struct Lambofile {
    /// Project name (defaults to the directory name when absent).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// PHP version specification (`stable`, `8.4`, `^8.3`, …).
    pub php: VersionSpec,
    /// Web server settings.
    pub server: ServerSettings,
    /// Database settings.
    pub database: DatabaseSettings,
    /// Open the browser after `lambo up`; `None` inherits `browser.open`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub open_browser: Option<bool>,
    /// PHP extensions to enable for this project.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub extensions: Vec<String>,
    /// Extra environment values merged into generated `.env` files.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub env: BTreeMap<String, String>,
}

/// How a project file was found: the current name or the legacy one.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Source {
    /// `lambo.yml`.
    Current,
    /// `kingphp.yml`, converted on the fly.
    Legacy,
}

impl Source {
    /// File name this source reads.
    pub fn file_name(self) -> &'static str {
        match self {
            Self::Current => FILE_NAME,
            Self::Legacy => LEGACY_FILE_NAME,
        }
    }
}

/// A loaded project file together with where it came from.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Loaded {
    /// The parsed configuration.
    pub file: Lambofile,
    /// Absolute path of the file that was read.
    pub path: PathBuf,
    /// Whether it came from the legacy king-PHP name.
    pub source: Source,
}

/// The old king-PHP project schema, read only for migration.
///
/// Fields Lambo no longer uses (`ssl`, `domain`) are accepted and dropped so
/// an existing file keeps loading; `document_root: null` becomes `.`.
#[derive(Debug, Deserialize)]
#[serde(default)]
struct LegacyKingfile {
    php: VersionSpec,
    server: ServerKind,
    database: DatabaseKind,
    #[serde(default)]
    ssl: bool,
    #[serde(default)]
    extensions: Vec<String>,
    #[serde(default)]
    name: Option<String>,
    #[serde(default)]
    domain: Option<String>,
    #[serde(default)]
    document_root: Option<String>,
    #[serde(default)]
    env: BTreeMap<String, String>,
}

impl Default for LegacyKingfile {
    fn default() -> Self {
        Self {
            php: VersionSpec::Stable,
            server: ServerKind::Apache,
            database: DatabaseKind::None,
            ssl: true,
            extensions: Vec::new(),
            name: None,
            domain: None,
            document_root: None,
            env: BTreeMap::new(),
        }
    }
}

impl Lambofile {
    /// Full path of the project file inside `dir`.
    pub fn path_in(dir: &Path) -> PathBuf {
        dir.join(FILE_NAME)
    }

    /// Whether `dir` directly contains a `lambo.yml`.
    pub fn exists_in(dir: &Path) -> bool {
        Self::path_in(dir).is_file()
    }

    /// Loads the project file of `dir`; `Ok(None)` when absent.
    pub fn load(dir: &Path) -> Result<Option<Self>> {
        Ok(Self::load_with_source(dir)?.map(|loaded| loaded.file))
    }

    /// Loads the project file, also reporting a legacy `kingphp.yml`.
    pub fn load_with_source(dir: &Path) -> Result<Option<Loaded>> {
        for source in [Source::Current, Source::Legacy] {
            let path = dir.join(source.file_name());
            let text = match fs::read_to_string(&path) {
                Ok(text) => text,
                Err(error) if error.kind() == ErrorKind::NotFound => continue,
                Err(error) => return Err(Error::io(&path, error)),
            };
            let file = match source {
                Source::Current => yaml::from_str(&text).map_err(|source| Error::Yaml {
                    path: path.clone(),
                    source,
                })?,
                Source::Legacy => convert_legacy(&text, &path)?,
            };
            return Ok(Some(Loaded { file, path, source }));
        }
        Ok(None)
    }

    /// Writes the file (with header) into `dir`, returning its path.
    pub fn save(&self, dir: &Path) -> Result<PathBuf> {
        let path = Self::path_in(dir);
        let body = yaml::to_string(self).map_err(Error::Serialize)?;
        crate::fsx::write_atomic(&path, &format!("{HEADER}{body}"))?;
        Ok(path)
    }

    /// Finds the enclosing project by walking upwards from `start`.
    ///
    /// Returns the project root together with the loaded file, so commands
    /// work from any subdirectory of a project.
    pub fn find(start: &Path) -> Result<Option<(PathBuf, Loaded)>> {
        for dir in start.ancestors() {
            if let Some(loaded) = Self::load_with_source(dir)? {
                return Ok(Some((dir.to_path_buf(), loaded)));
            }
        }
        Ok(None)
    }

    /// Rewrites a legacy `kingphp.yml` as `lambo.yml`.
    ///
    /// Returns the path written, or `None` when there was nothing to migrate.
    /// The legacy file is left in place: removing a user's file is never
    /// Lambo's decision, and the two can coexist because `lambo.yml` wins.
    pub fn migrate_legacy(dir: &Path) -> Result<Option<PathBuf>> {
        let Some(loaded) = Self::load_with_source(dir)? else {
            return Ok(None);
        };
        if loaded.source != Source::Legacy {
            return Ok(None);
        }
        Ok(Some(loaded.file.save(dir)?))
    }

    /// Project name: explicit, else the directory name.
    pub fn project_name(&self, dir: &Path) -> String {
        self.name
            .clone()
            .filter(|name| !name.trim().is_empty())
            .unwrap_or_else(|| {
                dir.file_name()
                    .map(|name| name.to_string_lossy().into_owned())
                    .filter(|name| !name.is_empty())
                    .unwrap_or_else(|| "app".to_owned())
            })
    }

    /// Effective HTTP port: the project's, else the global default.
    pub fn http_port(&self, config: &Config) -> u16 {
        self.server.port.unwrap_or(config.server.port)
    }

    /// Effective HTTPS port.
    pub fn https_port(&self, config: &Config) -> u16 {
        self.server.https_port.unwrap_or(config.server.https_port)
    }

    /// Effective database port.
    pub fn database_port(&self, config: &Config) -> u16 {
        self.database.port.unwrap_or(config.database.port)
    }

    /// Effective database name.
    pub fn database_name(&self, dir: &Path) -> String {
        self.database
            .name
            .clone()
            .filter(|name| !name.trim().is_empty())
            .unwrap_or_else(|| naming::database_name(&self.project_name(dir)))
    }

    /// Whether the browser should open after `lambo up`.
    pub fn should_open_browser(&self, config: &Config) -> bool {
        self.open_browser.unwrap_or(config.browser.open)
    }

    /// Absolute document root for a project rooted at `dir`.
    pub fn document_root(&self, dir: &Path) -> PathBuf {
        let configured = self.server.document_root.trim();
        if configured.is_empty() || configured == "." {
            dir.to_path_buf()
        } else {
            dir.join(configured)
        }
    }

    /// Validates the file against the project it lives in.
    ///
    /// Called by `lambo init`, `lambo up` and `lambo doctor`, so an invalid
    /// file is caught before Apache is handed a configuration that cannot
    /// work.
    pub fn validate(&self, dir: &Path) -> Result<()> {
        let path = Self::path_in(dir);

        let root = self.server.document_root.trim();
        if root.is_empty() {
            return Err(invalid(
                &path,
                "`server.document_root` must not be empty (use `.`)",
            ));
        }
        let relative = Path::new(root);
        if relative.is_absolute()
            || root.starts_with('/')
            || root.contains('\\')
            || root.contains(':')
        {
            return Err(invalid(
                &path,
                "`server.document_root` must be relative to the project root (for example `public`)",
            ));
        }
        if relative
            .components()
            .any(|component| matches!(component, std::path::Component::ParentDir))
        {
            return Err(invalid(
                &path,
                "`server.document_root` must not point outside the project (`..`)",
            ));
        }

        for (key, port) in [
            ("server.port", self.server.port),
            ("server.https_port", self.server.https_port),
            ("database.port", self.database.port),
        ] {
            if port == Some(0) {
                return Err(invalid(
                    &path,
                    &format!("`{key}` must be between 1 and 65535"),
                ));
            }
        }

        if matches!(self.server.kind, Some(ServerKind::Nginx)) {
            return Err(invalid(
                &path,
                "`server.kind: nginx` is not supported yet (use apache)",
            ));
        }

        if let Some(name) = &self.name {
            if !platform::is_valid_path_component(name) {
                return Err(invalid(
                    &path,
                    &format!("`name: {name}` is not usable as a directory or database name"),
                ));
            }
        }

        if let Some(database) = &self.database.name {
            if !naming::is_valid_database_name(database) {
                return Err(invalid(
                    &path,
                    &format!("`database.name: {database}` is not a valid MySQL identifier"),
                ));
            }
        }

        for extension in &self.extensions {
            if extension.trim().is_empty()
                || extension.contains('/')
                || extension.contains('\\')
                || extension.contains("..")
            {
                return Err(invalid(
                    &path,
                    &format!("`extensions` entry `{extension}` is not a PHP extension name"),
                ));
            }
        }

        Ok(())
    }
}

/// Converts a `kingphp.yml` document into the current schema.
fn convert_legacy(text: &str, path: &Path) -> Result<Lambofile> {
    let legacy: LegacyKingfile = yaml::from_str(text).map_err(|source| Error::Yaml {
        path: path.to_path_buf(),
        source,
    })?;
    let _ = (legacy.ssl, legacy.domain); // intentionally dropped
    Ok(Lambofile {
        name: legacy.name,
        php: legacy.php,
        server: ServerSettings {
            kind: Some(legacy.server),
            port: None,
            https_port: None,
            document_root: legacy.document_root.unwrap_or_else(|| ".".to_owned()),
        },
        database: DatabaseSettings {
            kind: Some(legacy.database),
            port: None,
            name: None,
        },
        open_browser: None,
        extensions: legacy.extensions,
        env: legacy.env,
    })
}

/// Builds an [`Error::InvalidProjectFile`].
fn invalid(path: &Path, reason: &str) -> Error {
    Error::InvalidProjectFile {
        path: path.to_path_buf(),
        reason: reason.to_owned(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testutil::TempDir;

    #[test]
    fn save_then_load_roundtrips() {
        let temp = TempDir::new();
        let file = Lambofile {
            name: Some("shop".to_owned()),
            php: "8.4".parse().unwrap(),
            server: ServerSettings {
                document_root: "public".to_owned(),
                port: Some(8080),
                ..ServerSettings::default()
            },
            database: DatabaseSettings {
                kind: Some(DatabaseKind::Mariadb),
                port: Some(3306),
                name: Some("shop".to_owned()),
            },
            open_browser: Some(true),
            extensions: vec!["redis".to_owned(), "imagick".to_owned()],
            ..Lambofile::default()
        };

        let path = file.save(temp.path()).unwrap();
        assert!(path.ends_with(FILE_NAME));

        let raw = fs::read_to_string(&path).unwrap();
        assert!(raw.starts_with("# Lambo PHP project configuration"));
        assert!(raw.contains("document_root: public"));
        assert!(raw.contains("kind: mariadb"));
        assert!(raw.contains("- redis"));

        let loaded = Lambofile::load(temp.path()).unwrap().unwrap();
        assert_eq!(loaded, file);
    }

    #[test]
    fn empty_document_yields_defaults() {
        let temp = TempDir::new();
        fs::write(temp.path().join(FILE_NAME), "{}\n").unwrap();
        let loaded = Lambofile::load(temp.path()).unwrap().unwrap();
        assert_eq!(loaded, Lambofile::default());
        assert_eq!(loaded.server.document_root, ".");
    }

    #[test]
    fn the_documented_example_parses() {
        let temp = TempDir::new();
        fs::write(
            temp.path().join(FILE_NAME),
            "\
name: my-project
php: 8.4
server:
  kind: apache
  port: 8080
  document_root: public
database:
  kind: mariadb
  port: 3306
open_browser: true
",
        )
        .unwrap();

        let file = Lambofile::load(temp.path()).unwrap().unwrap();
        assert_eq!(file.name.as_deref(), Some("my-project"));
        assert_eq!(file.php.to_string(), "~8.4");
        assert_eq!(file.server.kind, Some(ServerKind::Apache));
        assert_eq!(file.server.port, Some(8080));
        assert_eq!(file.server.document_root, "public");
        assert_eq!(file.database.kind, Some(DatabaseKind::Mariadb));
        assert_eq!(file.database.port, Some(3306));
        assert_eq!(file.open_browser, Some(true));
    }

    #[test]
    fn missing_file_is_none_not_error() {
        let temp = TempDir::new();
        assert_eq!(Lambofile::load(temp.path()).unwrap(), None);
        assert!(!Lambofile::exists_in(temp.path()));
    }

    #[test]
    fn find_walks_upwards() {
        let temp = TempDir::new();
        Lambofile::default().save(temp.path()).unwrap();
        let nested = temp.path().join("app/Http/Controllers");
        fs::create_dir_all(&nested).unwrap();

        let (root, loaded) = Lambofile::find(&nested).unwrap().unwrap();
        assert_eq!(root, temp.path());
        assert_eq!(loaded.source, Source::Current);
    }

    #[test]
    fn legacy_kingphp_file_is_read_and_converted() {
        let temp = TempDir::new();
        fs::write(
            temp.path().join(LEGACY_FILE_NAME),
            "\
php: ^8.2
server: apache
database: mariadb
ssl: true
domain: shop.test
document_root: public
name: shop
extensions: [redis]
",
        )
        .unwrap();

        let loaded = Lambofile::load_with_source(temp.path()).unwrap().unwrap();
        assert_eq!(loaded.source, Source::Legacy);
        assert_eq!(loaded.file.server.document_root, "public");
        assert_eq!(loaded.file.database.kind, Some(DatabaseKind::Mariadb));
        assert_eq!(loaded.file.name.as_deref(), Some("shop"));
        assert_eq!(loaded.file.extensions, vec!["redis".to_owned()]);
        assert_eq!(loaded.file.php.to_string(), "^8.2");

        // A legacy file with no document_root serves the project root.
        let plain = TempDir::new();
        fs::write(plain.path().join(LEGACY_FILE_NAME), "server: apache\n").unwrap();
        let plain_file = Lambofile::load(plain.path()).unwrap().unwrap();
        assert_eq!(plain_file.server.document_root, ".");
    }

    #[test]
    fn migration_writes_lambo_yml_and_keeps_the_old_file() {
        let temp = TempDir::new();
        fs::write(temp.path().join(LEGACY_FILE_NAME), "database: mariadb\n").unwrap();

        let written = Lambofile::migrate_legacy(temp.path()).unwrap().unwrap();
        assert_eq!(written, temp.path().join(FILE_NAME));
        assert!(
            temp.path().join(LEGACY_FILE_NAME).exists(),
            "the old file must not be deleted"
        );
        assert_eq!(
            Lambofile::load_with_source(temp.path())
                .unwrap()
                .unwrap()
                .source,
            Source::Current,
            "lambo.yml takes precedence once written"
        );

        // Nothing to migrate twice.
        assert!(Lambofile::migrate_legacy(temp.path()).unwrap().is_none());
    }

    #[test]
    fn effective_values_inherit_from_global_config() {
        let config = Config::default();
        let mut file = Lambofile::default();

        assert_eq!(file.http_port(&config), 80, "inherits the global default");
        assert_eq!(file.database_port(&config), 3306);
        assert!(file.should_open_browser(&config));

        file.server.port = Some(9000);
        file.open_browser = Some(false);
        assert_eq!(file.http_port(&config), 9000);
        assert!(!file.should_open_browser(&config));
    }

    #[test]
    fn document_root_resolves_relative_to_the_project() {
        let temp = TempDir::new();
        let root = temp.path().join("shop");
        let mut file = Lambofile::default();

        file.server.document_root = "public".to_owned();
        assert_eq!(file.document_root(&root), root.join("public"));
        file.server.document_root = ".".to_owned();
        assert_eq!(file.document_root(&root), root);
        file.server.document_root = "".to_owned();
        assert_eq!(file.document_root(&root), root);
    }

    #[test]
    fn project_and_database_names_fall_back_sensibly() {
        let temp = TempDir::new();
        let dir = temp.path().join("My Shop");
        let mut file = Lambofile::default();

        assert_eq!(file.project_name(&dir), "My Shop");
        assert_eq!(file.database_name(&dir), "my_shop");

        file.name = Some("storefront".to_owned());
        assert_eq!(file.project_name(&dir), "storefront");
        assert_eq!(file.database_name(&dir), "storefront");

        file.database.name = Some("shop_dev".to_owned());
        assert_eq!(file.database_name(&dir), "shop_dev");
    }

    #[test]
    fn validation_rejects_machine_specific_and_escaping_paths() {
        let temp = TempDir::new();
        let root = temp.path();

        let mut file = Lambofile::default();
        file.validate(root).unwrap();

        file.server.document_root = r"C:\Lambo\shop\public".to_owned();
        let error = file.validate(root).unwrap_err();
        assert!(error.to_string().contains("relative"), "{error}");

        file.server.document_root = "/var/www".to_owned();
        assert!(file.validate(root).is_err());

        file.server.document_root = "../outside".to_owned();
        assert!(file.validate(root).is_err());

        file.server.document_root = "public".to_owned();
        file.validate(root).unwrap();
    }

    #[test]
    fn validation_rejects_unusable_names_and_ports() {
        let temp = TempDir::new();
        let root = temp.path();

        let file = Lambofile {
            server: ServerSettings {
                port: Some(0),
                ..ServerSettings::default()
            },
            ..Lambofile::default()
        };
        assert!(file.validate(root).is_err());

        let file = Lambofile {
            name: Some("con".to_owned()),
            ..Lambofile::default()
        };
        assert!(
            file.validate(root).is_err(),
            "reserved Windows names must be rejected"
        );

        let file = Lambofile {
            database: DatabaseSettings {
                name: Some("1bad-name".to_owned()),
                ..DatabaseSettings::default()
            },
            ..Lambofile::default()
        };
        assert!(file.validate(root).is_err());

        let file = Lambofile {
            server: ServerSettings {
                kind: Some(ServerKind::Nginx),
                ..ServerSettings::default()
            },
            ..Lambofile::default()
        };
        assert!(file.validate(root).is_err());

        let file = Lambofile {
            extensions: vec!["../../evil".to_owned()],
            ..Lambofile::default()
        };
        assert!(file.validate(root).is_err());
    }

    #[test]
    fn optional_fields_are_omitted_when_serialized() {
        let raw = yaml::to_string(&Lambofile::default()).unwrap();
        assert!(!raw.contains("extensions:"));
        assert!(!raw.contains("name:"));
        assert!(!raw.contains("open_browser:"));
        assert!(raw.contains("php: stable"));
        assert!(raw.contains("document_root: ."));

        // An unset engine or server is *omitted*, not written as a value: that
        // is what lets the global configuration decide, per the documented
        // global -> project hierarchy.
        assert!(
            !raw.contains("kind:"),
            "an inherited setting must not be pinned:\n{raw}"
        );

        // ...while an explicit choice is written, including the explicit "none"
        // that turns a database off for one project.
        let mut file = Lambofile::default();
        file.database.kind = Some(DatabaseKind::None);
        file.server.kind = Some(ServerKind::Php);
        let raw = yaml::to_string(&file).unwrap();
        assert!(raw.contains("kind: none"), "{raw}");
        assert!(raw.contains("kind: php"), "{raw}");
    }
}
